### this is simply a tidied version of the CTD_masterdf_exploratory.R file
# this file calls on other data files that haave been generated by previous scripts
# where this has happened, the name of the script is noted above

######################
### set the environment


graphics.off()
rm(list = ls())
load("pathway.Rdata") # data created in CTD*exploratory

setwd(pathway.to.linux)

# now set actually set the working directory within linux operating system
setwd("PhDCH1/Code/")

######################
# and load in my DF of all the relevant CTD files

load("../Data/BODC/MoreRelevantFiles.Rdata") # generated in CTD*exploratory
rm(all.df) # not necessary


######################
### load in necessary packages

library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting
library(chron) # converts julian dates (important!)

path.to.data <- "../Data/BODC/AllCDTData/"


######################
# prime the counter and the dataframes
path.to.data <- "../Data/BODC/AllCDTData/"

counter <- 0
  
  
master.df <- data.frame(I = NA, DATE = NA, JULIANINFO = NA, PRESS = NA, 
                        PRESSTXT = NA, CONDUCTIVITY = NA, 
                        TEMPERATURE = NA, TEMPERATURE_UNIT = NA, 
                        SALINITY = NA, 
                        SALINITY_UNIT = NA, 
                        LAT = NA, 
                        LONG = NA, CRUISEID = NA, MAXDEPTH = NA, 
                        DEPTH = NA, FILE = NA)

holding.df <-  master.df

######################
################ LOOP
######################

for (i in 1:length(r.df$file)) {
  # to ensure we're not carrying over data, we resset the holding data frame to be empty each time
  holding.df <- data.frame(I = NA, DATE = NA, JULIANINFO = NA, PRESS = NA, 
                           PRESSTXT = NA, CONDUCTIVITY = NA, 
                           TEMPERATURE = NA, TEMPERATURE_UNIT = NA, 
                           SALINITY = NA, 
                           SALINITY_UNIT = NA, 
                           LAT = NA, 
                           LONG = NA, CRUISEID = NA, MAXDEPTH = NA, 
                           DEPTH = NA, FILE = NA)
  
  # we then open the .nc file (one at a time)
  # w.data the "w." prefix here is "working" - ie will change every time
  w.data <- nc_open(file = paste(path.to.data, r.df$file[i], sep = ""))
  # store variables
  
  # WORK OUT HOW THE DEPTH HAS BEEN STORED - AS PRESSURE OR AS DEPTH? ?
  # if they have both - then use depth (more accurate?) but also record pressure
  
  
  if(length(w.data$var$PRES) > 0) {
    w.pressure <- ncvar_get(w.data, "PRES")
    # we now re-initialise the dataframe, this time using the single re-extracted variable
    #  this makes the length of the df correct!
    holding.df <- data.frame(I = NA, DATE = NA, JULIANINFO = NA, PRESS = w.pressure, 
                             PRESSTXT = NA, CONDUCTIVITY = NA, 
                             TEMPERATURE = NA, TEMPERATURE_UNIT = NA, 
                             SALINITY = NA, SALINITY_UNIT = NA, 
                             LAT = NA, 
                             LONG = NA, CRUISEID = NA, MAXDEPTH = NA, 
                             DEPTH = NA, FILE = NA)
    holding.df$PRESSTXT <- w.data$var$PRES$units
  }
  
  # however, it might be that it's stored directly as 'depth' (which is GREAT)
  
  if (length(w.data$var$DEPTH) > 0) {
    w.depth <- ncvar_get(w.data, "DEPTH")
    holding.df <- data.frame(I = NA, DATE = NA, JULIANINFO = NA, PRESS = NA, 
                             PRESSTXT = NA, CONDUCTIVITY = NA, 
                             TEMPERATURE = NA, TEMPERATURE_UNIT = NA,  
                             SALINITY = NA, 
                             SALINITY_UNIT = NA, 
                             LAT = NA, 
                             LONG = NA, CRUISEID = NA, MAXDEPTH = NA, 
                             DEPTH = w.depth, FILE = NA)
    
  }
  
  if ((length(w.data$var$PRES) > 0) & (length(w.data$var$DEPTH) > 0)) {
    holding.df$PRESS <- w.pressure
    holding.df$PRESSTXT <- w.data$var$PRES$units
  } 
  
  # and now we insert the rest of the data
  holding.df$I <- i
  holding.df$FILE <- r.df$file[i]
  try(holding.df$DATE <- ncvar_get(w.data, "TIME"), silent = F, outFile = "Error - date")
  # now put in the data that we will use to convert the Julian date
  try(holding.df$JULIANINFO <- w.data$var$TIME$units)
  #holding.df$CONDUCTIVITY <- ncvar_get(w.data
  try(holding.df$LAT <- ncvar_get(w.data, "LATITUDE"))
  try(holding.df$LONG <- ncvar_get(w.data, "LONGITUDE"))
  try(holding.df$MAXDEPTH <- ncvar_get(w.data, "SDN_BOT_DEPTH"), silent = F, outFile = "Error - max depth")
  
  ## different types of salinity need to be captured 
  
  if (length(w.data$var$PSALPR01) > 0) {
    holding.df$SALINITY <- ncvar_get(w.data, "PSALPR01")
    holding.df$SALINITY_UNIT <- w.data$var$PSALPR01$units }
  
  if (length(w.data$var$SSALPR01) > 0) {
    
    holding.df$SALINITY <- ncvar_get(w.data, "SSALPR01")
    holding.df$SALINITY_UNIT <- w.data$var$SSALPR01$units }
  
  
  ## and different types of temperature
  
  if (length(w.data$var$TEMPST01) > 0) {
    holding.df$TEMPERATURE <- ncvar_get(w.data, "TEMPST01")
    holding.df$TEMPERATURE_UNIT <- w.data$var$TEMPST01$units }
  
  if (length(w.data$var$TEMPPR01) > 0) {
    
    holding.df$TEMPERATURE <- ncvar_get(w.data, "TEMPPR01")
    holding.df$TEMPERATURE <- w.data$var$TEMPPR01$units }
  
  try(holding.df$CRUISEID <- w.data$id)
  
  ### once all data gathered, then we concatenate to the master df 
  
  
  master.df <- rbind(master.df, holding.df)
  
  nc_close(w.data)
  
  
  if (i %% 100 == 0) {
    print(i)  
    
  }
  
  
}

# will then need to save the final version of the master df


save(master.df, file = "../Data/CTD_master_withTemp.Rdata")


####### THIS SHOULD RESULT IN: SINGLE Rdata files that contain only the information that we are interestd in 




